// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkbgklcgoaqgsglzpkjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYmdrbGNnb2FxZ3NnbHpwa2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjYwMTcsImV4cCI6MjA1MzI0MjAxN30.x6412uoTEwYZJ-QKYaSlQJrHMXf9cBHU-nU2ZvVrDYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);