
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Try to get from localStorage if running in browser
let SUPABASE_URL = "https://zkbgklcgoaqgsglzpkjx.supabase.co";
let SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYmdrbGNnb2FxZ3NnbHpwa2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjYwMTcsImV4cCI6MjA1MzI0MjAxN30.x6412uoTEwYZJ-QKYaSlQJrHMXf9cBHU-nU2ZvVrDYM";

// In browser environment, check localStorage for credentials
if (typeof window !== 'undefined') {
  const storedUrl = localStorage.getItem("SUPABASE_URL");
  const storedKey = localStorage.getItem("SUPABASE_ANON_KEY");
  
  if (storedUrl) SUPABASE_URL = storedUrl;
  if (storedKey) SUPABASE_PUBLISHABLE_KEY = storedKey;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
